# ".vimrc":
#   type: "file"
#   url: "https://raw.githubusercontent.com/offa/nvim-config/master/.vimrc"
#   refreshPeriod: "168h"

# ".vimrc.bundles":
#   type: "file"
#   url: "https://raw.githubusercontent.com/offa/nvim-config/master/.vimrc.bundles"
#   refreshPeriod: "168h"

# ".config/nvim/autoload/plug.vim":
#   type: "file"
#   url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
#   refreshPeriod: "168h"

# ".config/wezterm":
#   type: "git-repo"
#   url: "https://github.com/KevinSilvester/wezterm-config.git"
  