#!/bin/zsh
#
# -*- mode: sh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# code: language=shell insertSpaces=true tabSize=2

ZGEN_LOADED=()
ZGEN_COMPLETIONS=()

export PATH=/opt/homebrew/bin:$PATH

zgenom oh-my-zsh

# If zsh-syntax-highlighting is bundled after zsh-history-substring-search,
# they break, so get the order right.
zgenom load zsh-users/zsh-syntax-highlighting
zgenom load zsh-users/zsh-history-substring-search

# Set keystrokes for substring searching
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# Tab complete rakefile targets.
zgenom load unixorn/rake-completion.zshplugin

# Automatically run zgenom update and zgenom selfupdate every 7 days.
zgenom load unixorn/autoupdate-zgenom

# Add my collection of miscellaneous utility functions.
zgenom load unixorn/jpb.zshplugin

# Colorize the things if you have grc installed. Well, some of the
# things, anyway.
zgenom load unixorn/warhol.plugin.zsh

# macOS helpers. This plugin is smart enough to detect when it isn't running
# on macOS and not load itself, so you can safely share the same plugin list
# across macOS and Linux/BSD.
zgenom load unixorn/tumult.plugin.zsh

# Warn you when you run a command that you've set an alias for without
# using the alias.
zgenom load djui/alias-tips

# Add my collection of git helper scripts.
zgenom load unixorn/git-extra-commands

# Add git aliases
zgenom load mdumitru/git-aliases

# Supercharge your history search with fzf
zgenom load unixorn/fzf-zsh-plugin

# A collection of scripts that might be useful to sysadmins.
zgenom load skx/sysadmin-util

# Adds aliases to open your current repo & branch on github.
zgenom load peterhurford/git-it-on.zsh

# Load some oh-my-zsh plugins

zgenom oh-my-zsh plugins/aws
zgenom oh-my-zsh plugins/colored-man-pages
zgenom oh-my-zsh plugins/colorize
zgenom oh-my-zsh plugins/extract
zgenom oh-my-zsh plugins/gitfast
zgenom oh-my-zsh plugins/github
zgenom oh-my-zsh plugins/kubectl
zgenom oh-my-zsh plugins/kubectx
zgenom oh-my-zsh plugins/kube-ps1
zgenom oh-my-zsh plugins/pip
zgenom oh-my-zsh plugins/python
zgenom oh-my-zsh plugins/ripgrep
zgenom oh-my-zsh plugins/rsync
zgenom oh-my-zsh plugins/sudo
zgenom oh-my-zsh plugins/terraform
zgenom oh-my-zsh plugins/vscode

if [[ $(uname -a | grep -ci Darwin) = 1 ]]; then
  # Load macOS-specific plugins
  zgenom oh-my-zsh plugins/brew
  zgenom oh-my-zsh plugins/osx
fi


# A set of shell functions to make it easy to install small apps and
# utilities distributed with pip.
zgenom load sharat87/pip-app

zgenom load chrissicool/zsh-256color

# Load more completion files for zsh from the zsh-lovers github repo.
zgenom load zsh-users/zsh-completions src

# Docker completion
zgenom load srijanshetty/docker-zsh

zgenom load zpm-zsh/autoenv
zgenom load zpm-zsh/clipboard
zgenom load zpm-zsh/colorize
zgenom load zpm-zsh/colors
zgenom load olets/zsh-abbr
zgenom load agkozak/zsh-z
zgenom load hschne/fzf-git
zgenom load andrewferrier/fzf-z
zgenom load reegnz/jq-zsh-plugin
zgenom load droctothorpe/kubecolor
zgenom load hcgraf/zsh-sudo
zgenom load hlissner/zsh-autopair
zgenom load seanb4t/op.plugin.zsh
zgenom load seanb4t/zsh-aliases
zgenom load rbirnie/oh-my-zsh-keybase
zgenom load gradle/gradle-completion

 # Install ohmyzsh osx plugin if on macOS
[[ "$(uname -s)" = Darwin ]] && zgenom ohmyzsh plugins/osx

zgenom load dbz/kube-aliases

# Load me last
GENCOMPL_FPATH=$HOME/.zsh/complete

# Very cool plugin that generates zsh completion functions for commands
# if they have getopt-style help text. It doesn't generate them on the fly,
# you'll have to explicitly generate a completion, but it's still quite cool.
zgenom load RobSis/zsh-completion-generator

# Add Fish-like autosuggestions to your ZSH.
zgenom load zsh-users/zsh-autosuggestions

# k is a zsh script / plugin to make directory listings more readable,
# adding a bit of color and some git status information on files and
# directories.
zgenom load supercrabtree/k

zgenom load romkatv/powerlevel10k powerlevel10k

# Save it all to init script
zgenom save
