function lsa --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LA_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsa exa $EXA_STANDARD_OPTIONS $EXA_LA_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LA_OPTIONS $EXA_LS_OPTIONS $argv; 
end
