function lsaad --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAAD_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsaad exa $EXA_STANDARD_OPTIONS $EXA_LAAD_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LAAD_OPTIONS $EXA_LS_OPTIONS $argv; 
end
