function lsaa --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAA_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsaa exa $EXA_STANDARD_OPTIONS $EXA_LAA_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LAA_OPTIONS $EXA_LS_OPTIONS $argv; 
end
