function lsaaid --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAAID_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsaaid exa $EXA_STANDARD_OPTIONS $EXA_LAAID_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LAAID_OPTIONS $EXA_LS_OPTIONS $argv; 
end
