function lsaai --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsaai exa $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LS_OPTIONS $argv; 
end
