function lsad --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAD_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsad exa $EXA_STANDARD_OPTIONS $EXA_LAD_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LAD_OPTIONS $EXA_LS_OPTIONS $argv; 
end
