function lsai --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAI_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsai exa $EXA_STANDARD_OPTIONS $EXA_LAI_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LAI_OPTIONS $EXA_LS_OPTIONS $argv; 
end
