function lsaid --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LAID_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsaid exa $EXA_STANDARD_OPTIONS $EXA_LAID_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LAID_OPTIONS $EXA_LS_OPTIONS $argv; 
end
