function lsd --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LD_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsd exa $EXA_STANDARD_OPTIONS $EXA_LD_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LD_OPTIONS $EXA_LS_OPTIONS $argv; 
end
