function lsi --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsi exa $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LS_OPTIONS $argv; 
end
