function lsid --wraps='exa $EXA_STANDARD_OPTIONS $EXA_LID_OPTIONS $EXA_LS_OPTIONS' --description 'alias lsid exa $EXA_STANDARD_OPTIONS $EXA_LID_OPTIONS $EXA_LS_OPTIONS'
  exa $EXA_STANDARD_OPTIONS $EXA_LID_OPTIONS $EXA_LS_OPTIONS $argv; 
end
